# Generated by Django 6.1 on 2026-08-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='category',
            field=models.CharField(choices=[('software', 'Software Engineering'), ('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('fullstack', 'Full Stack Development'), ('design', 'UI / UX Design'), ('data', 'Data / AI'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
